const { test } = require('@playwright/test');
const { startGame, clearBoons, faceOpenGround, placeMonster } = require('./helpers');
const D = '/tmp/claude-0/-home-user-Dungeon-Hack-Mobile/0ea3aa4c-4ff7-53aa-a82b-10845959c612/scratchpad/shots/';
test('tour', async ({ page }) => {
  await page.goto('/');
  await page.waitForTimeout(900);
  await page.screenshot({ path: D + '01-title.png' });
  await page.click('#btn-new');
  await page.waitForTimeout(300);
  await page.screenshot({ path: D + '02-create.png', fullPage: true });
  await page.fill('#c-seed', 'tour');
  await page.click('#c-begin');
  await page.waitForTimeout(400);
  await page.screenshot({ path: D + '03-prologue.png' });
  await page.click('#pro-begin');
  await page.waitForTimeout(700);
  await clearBoons(page);
  await page.screenshot({ path: D + '04-start.png' });
  await faceOpenGround(page, 3);
  await placeMonster(page, 'goblin', 2, { hp: 30, maxHp: 30 });
  await placeMonster(page, 'skeleton', 4, { hp: 30, maxHp: 30 });
  await page.waitForTimeout(500);
  await page.screenshot({ path: D + '05-monsters.png' });
  await page.evaluate(() => { const p = Game.player(); for (let i = 0; i < 6; i++) { Game.state().t = p.nextAttack; Game.input('attack'); } });
  await page.waitForTimeout(200);
  await page.screenshot({ path: D + '06-combat.png' });
  await page.click('[data-open="inv"]'); await page.waitForTimeout(300);
  await page.screenshot({ path: D + '07-inv.png' });
  await page.keyboard.press('Escape');
  await page.evaluate(() => Game.level().explored.fill(1));
  await page.click('[data-open="map"]'); await page.waitForTimeout(300);
  await page.screenshot({ path: D + '08-map.png' });
  await page.keyboard.press('Escape');
  await page.click('[data-open="char"]'); await page.waitForTimeout(300);
  await page.screenshot({ path: D + '09-char.png' });
  await page.keyboard.press('Escape');
});
